# Generated by Django 4.2 on 2023-06-13 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NoteModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tittle", models.CharField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("createdAt", models.DateField(auto_now_add=True)),
                ("UpdatedAt", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "notes",
                "ordering": ["createdAt"],
            },
        ),
    ]
